### ISSUE TITLE
Problemes with SAML Authentication

### ISSUE THREAD

**Issue by spranta1977** [splunk/ta-cisco-webex-meetings-add-on-for-splunk#17]
Hello,

we wanted to use the TA in our company but having troubles getting the data. We have got SAML configured @ our Webex Site and it seems to be the App can't handle SAML Authentication.
We are getting the following Errors
 2020-07-31 11:39:57,536 INFO pid=10200 tid=MainThread file=setup_util.py:log_info:117 | Customized key can not be found
2020-07-31 11:39:57,538 INFO pid=10200 tid=MainThread file=splunk_rest_client.py:_request_handler:105 | Use HTTP connection pooling
2020-07-31 11:39:57,562 ERROR pid=10200 tid=MainThread file=base_modinput.py:log_error:309 | Get error when collecting events.
Traceback (most recent call last):
  File "C:\Program Files\Splunk\etc\apps\ta-cisco-webex-meetings-add-on-for-splunk\bin\ta_cisco_webex_meetings_add_on_for_splunk\aob_py2\modinput_wrapper\base_modinput.py", line 128, in stream_events
    self.collect_events(ew)
  File "C:\Program Files\Splunk\etc\apps\ta-cisco-webex-meetings-add-on-for-splunk\bin\general_service.py", line 64, in collect_events
    input_module.collect_events(self, ew)
  File "C:\Program Files\Splunk\etc\apps\ta-cisco-webex-meetings-add-on-for-splunk\bin\input_module_general_service.py", line 122, in collect_events
    end_time_epoch = datetime.utcnow().strftime("%s")
ValueError: Invalid format string

Thanks
Alex

**Comment by mayurah** [comment]
Hey @spranta1977 ,  at the moment SAML is short-lived and not directly implemented in TA's user interface.

For the error, you may use [patched version](https://drive.google.com/drive/u/0/folders/1E3Aq7fgJmYkId1P0Z0_40fZtk_I0aToG)

Alex, let us know in case you need any further clarity.

**Comment by spranta1977** [comment]
Hi Mayurah,
thanks for the fixed version. 
2020-07-31 15:03:32,445 INFO pid=10128 tid=MainThread file=setup_util.py:log_info:117 | Customized key can not be found
2020-07-31 15:03:32,446 INFO pid=10128 tid=MainThread file=splunk_rest_client.py:_request_handler:105 | Use HTTP connection pooling
2020-07-31 15:04:29,784 INFO pid=1260 tid=MainThread file=setup_util.py:log_info:117 | Customized key can not be found
2020-07-31 15:04:29,785 INFO pid=1260 tid=MainThread file=splunk_rest_client.py:_request_handler:105 | Use HTTP connection pooling
I'm now having only those messages. But it seems to be i'm still not getting any data.

Just for clarity, SSO is configured at webex using our ADFS. So the Service Account which is configured within the app normaly doesn't need a password. I hope my setup is correct. I installed a Heavyforwarder which is running with the same account as the webex service account. So if i open a web browser on the Heavyforwarder an open https://[site].webex.com i just have to enter the service account email adressen and i'm connected...

2020-07-31 16:42:02,081 DEBUG pid=1856 tid=MainThread file=base_modinput.py:log_debug:288 | timestamp_value: 07/31/2020 13:02:32
2020-07-31 16:42:02,084 DEBUG pid=1856 tid=MainThread file=base_modinput.py:log_debug:288 | type of start time: <class 'str'>
2020-07-31 16:42:02,084 DEBUG pid=1856 tid=MainThread file=base_modinput.py:log_debug:288 | ---start time---: 07/31/2020 13:02:33
2020-07-31 16:42:02,084 DEBUG pid=1856 tid=MainThread file=base_modinput.py:log_debug:288 | start time: 07/31/2020 13:02:33
2020-07-31 16:42:02,084 DEBUG pid=1856 tid=MainThread file=base_modinput.py:log_debug:288 | end time: 07/31/2020 14:42:02
2020-07-31 16:42:02,084 DEBUG pid=1856 tid=MainThread file=base_modinput.py:log_debug:288 | current_offset: 1
2020-07-31 16:42:02,084 DEBUG pid=1856 tid=MainThread file=base_modinput.py:log_debug:288 | == Live Data log ==
2020-07-31 16:42:02,085 DEBUG pid=1856 tid=MainThread file=base_modinput.py:log_debug:288 | [-] Debug Fetch Request: 1 - 500
2020-07-31 16:42:02,087 DEBUG pid=1856 tid=MainThread file=connectionpool.py:_new_conn:959 | Starting new HTTPS connection (1): egger.webex.com:443
2020-07-31 16:42:03,447 DEBUG pid=1856 tid=MainThread file=connectionpool.py:_make_request:437 | https://egger.webex.com:443 "POST /WBXService/XMLService HTTP/1.1" 200 None
2020-07-31 16:42:03,450 DEBUG pid=1856 tid=MainThread file=base_modinput.py:log_debug:288 | [-] : response.status_code: 200
2020-07-31 16:42:03,451 DEBUG pid=1856 tid=MainThread file=base_modinput.py:log_debug:288 | {'header': {'response': {'result': 'FAILURE', 'reason': 'Incorrect user or password', 'gsbStatus': 'PRIMARY', 'exceptionID': '030002'}}, 'body': {'bodyContent': None}}
2020-07-31 16:42:03,451 DEBUG pid=1856 tid=MainThread file=base_modinput.py:log_debug:288 | [-] WebEx Response: 'Incorrect user or password'

Is there a different way to configure this configuration within the app...
Thanks
Alex


Oh,i had to add some emojis :) 👯 👍 🖐️

**Comment by suskirge** [comment]
Our WebEx is also SSO enabled and syncing with Active Directory. Cannot see anywhere in admin.webex.com where to create a locally (webex) authenticated account.


2020-08-06 16:38:05,962 DEBUG pid=45769 tid=MainThread file=base_modinput.py:log_debug:288 | == Live Data log ==
2020-08-06 16:38:05,962 DEBUG pid=45769 tid=MainThread file=base_modinput.py:log_debug:288 | [-] Debug Fetch Request: 1 - 500
2020-08-06 16:38:05,964 DEBUG pid=45769 tid=MainThread file=connectionpool.py:_new_conn:959 | Starting new HTTPS connection (1): sitename.webex.com:443
2020-08-06 16:38:08,846 DEBUG pid=45769 tid=MainThread file=connectionpool.py:_make_request:437 | https://sitename.webex.com:443 "POST /WBXService/XMLService HTTP/1.1" 200 None
2020-08-06 16:38:08,849 DEBUG pid=45769 tid=MainThread file=base_modinput.py:log_debug:288 | [-] : response.status_code: 200
2020-08-06 16:38:08,849 DEBUG pid=45769 tid=MainThread file=base_modinput.py:log_debug:288 | {'header': {'response': {'result': 'FAILURE', 'reason': 'Incorrect user or password', 'gsbStatus': 'PRIMARY', 'exceptionID': '030002'}}, 'body': {'bodyContent': None}}
2020-08-06 16:38:08,850 DEBUG pid=45769 tid=MainThread file=base_modinput.py:log_debug:288 | [-] WebEx Response: 'Incorrect user or password'

**Comment by spranta1977** [comment]
As far as i know you can not create a locally autenticated account if SSO is enabled

**Comment by suskirge** [comment]
@spranta1977 Correct. Does this mean this ta is not usable?

**Comment by spranta1977** [comment]
@suskirge seems to be :( i havn't got any answer so far how to configure the TA is SSO is enabled (which is the most used webex configuration by the way...) But i will open a Support Case Ticket now

**Comment by mayurah** [comment]
@spranta1977  / @suskirge  - **SSO is not supported out of the box at the moment.**

Efforts are underway but there's no timeline as this is an open-source project and we would encourage community members to contribute for any specific feature.

Partly, SSO based auth token is short-lived, so we are exploring ways WebEx could have TA hold a session for longer than 14 days without needing re-auth.

**Comment by lindonm** [comment]
Also having this issue, company based ADFS. The TA would need to support following the redirect and logging in to the secondary web page (ADFS HTML login page) for this to be able to work from our cloud IDM, or support a secondary NTLM prompt if running from local HF.

I wish I knew python so that I could help :)

**Comment by spranta1977** [comment]
or cisco would a allow to configure a service user that isn't using SSO via ADFS  :/

**Comment by phwoelfel** [comment]
We managed to make it work using an integration and oAuth access/refresh token. We had to change some python files to make it work for our use case but I already have a more flexible way in my mind. Would it be possible to get the addon builder project files so I can implement the change correctly and then create a merge request?
